sudo: required
services:
  - docker

before_install:
  - docker build -t sydbarrett/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sydbarrett/react-test npm test

after_success:
  # Build Production docker images for all services
  - docker build -t sydbarrett/multi-client ./client
  - docker build -t sydbarrett/multi-nginx ./nginx
  - docker build -t sydbarrett/multi-server ./server
  - docker build -t sydbarrett/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push sydbarrett/multi-client
  - docker push sydbarrett/multi-nginx
  - docker push sydbarrett/multi-server
  - docker push sydbarrett/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-366225493403
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
